### ISSUE TITLE
CLI solve results different from GUI

### ISSUE THREAD

**Issue by GitterHubber** [Qalculate/libqalculate#119]
This works in the GUI

![image](https://user-images.githubusercontent.com/2816034/50200198-cbb45f80-037a-11e9-8bd4-13f7dffef9b8.png)

In the CLI it doesn't
![image](https://user-images.githubusercontent.com/2816034/50200297-54cb9680-037b-11e9-911b-c5f0830ad3d5.png)

I'm on Win7, 64bit

**Comment by hanna-kn** [comment]
That's because of how the command line is parsed. The expression is passed to qalc as multiple arguments and the quotation marks are then usually already removed by the command processor (shell). Using the above expression under Linux (using bash) will return with a syntax error, caused by the parentheses, before qalc is run.

To avoid this you should either put the whole expression in quotes (`qalc 'solve("volti" = "ampi" * "resi", "resi")'`) or use interactive mode (start qalc without any expression). 

Note that the CLI application generally does not work as well on Windows as on Unix-like operating systems.

**Comment by GitterHubber** [comment]
Thanks for the update.
I tried both single quote and double quotes but to no avail.
![image](https://user-images.githubusercontent.com/2816034/50244043-e4615b80-03f4-11e9-9e75-ccb2a0cac837.png)

I'm trying to talk to qalculate! via an external program. If command line is not suitable in Windows, is there any other way of getting data out of Qalculate?

**Comment by hanna-kn** [comment]
The multiplication sign is causing problems. It is interpreted as a wildcard character (or similar) by the command prompt. Removing spaces around the multiplication sign, or using a different multiplication sign (such as ×), and using single instead of double quotes (qalc `solve('volti' = 'ampi'*'resi', 'resi')` seem to workaround the issue in the Windows command prompt. You might get a different result when using qalc from an external program (or when using a different command-line interpreter).

**Comment by hanna-kn** [comment]
The user functions.xml has, for some unknown reason, been improperly saved. The error is harmless, but the underlying issue might not be. Does "C:\Users\XXXX\AppData\Local\Qalculate\definitions\variables.xml" exist and is it non-empty? Does the error return if you start and exit (write `exit`) qalc without any arguments and/or if you run qalculate (the GUI)? By default the user definition files are saved on exit (except when running qalc in non-interactive mode).

**Comment by hanna-kn** [comment]
Here is my final recommendation for usage of qalc in the Windows command prompt:
- Use double quotation marks (") at the beginning and end of the expression.
- Escape any double quotation marks within the expression (\"), or if feasible replace double with single quotation marks.

_Example: `qalc "solve(\"volti\" = \"ampi\" * \"resi\", \"resi\")"` or `qalc "solve('volti' = 'ampi' * 'resi', 'resi')"`_

When running qalc via an external program the -t (-terse) command line switch might be useful, if you only want the answer. It is often also a good idea to specify a maximum calculation time using -m (-time).

**Comment by GitterHubber** [comment]
> variables.xml

it exists only in 
"C:\Program Files (x86)\Qalculate\definitions\variables.xml" => 35KB

![image](https://user-images.githubusercontent.com/2816034/50279247-334bd700-046f-11e9-8dba-8b49ee8bcc79.png)

**Comment by GitterHubber** [comment]
> 
> 
> Here is my final recommendation for usage of qalc in the Windows command prompt:
> 
>     * Use double quotation marks (") at the beginning and end of the expression.
> 
>     * Escape any double quotation marks within the expression ("), or if feasible replace double with single quotation marks.
> 
> 
> _Example: `qalc "solve(\"volti\" = \"ampi\" * \"resi\", \"resi\")"` or `qalc "solve('volti' = 'ampi' * 'resi', 'resi')"`_
> 
> When running qalc via an external program the -t (-terse) command line switch might be useful, if you only want the answer. It is often also a good idea to specify a maximum calculation time using -m (-time).

The -t option is excellent, and many thanks for the suggestions.
Do I need to install qalculate! on the target PC to use qalc? Or will the qalc.exe along with some dll's suffice?

**Comment by GitterHubber** [comment]
Ok I wanted to try something complex now like
`f = 1/ (2  * pi * sqrt(L * C))` , thats the formula for resonant frequency, so I'm doing this

`qalc - t "solve('f'=1/(2 * 'PI' * 'sqrt('L' * 'C')'), 'C')"`
which doesn't work out

Now here there is another function "pi" and "sqrt" inside solve so how would this be entered.

**Comment by GitterHubber** [comment]
> Ok I wanted to try something complex now like
> `f = 1/ (2 * pi * sqrt(L * C))` , thats the formula for resonant frequency, so I'm doing this
> 
> `qalc -t "solve('f'=1/(2 * 'PI' * 'sqrt('L' * 'C')'), 'C')"`
> which doesn't work out
> 
> Now here there is another function "pi" and "sqrt" inside solve so how would this be entered.

Ok I got that to work with

`C:\Program Files (x86)\Qalculate>qalc -t "solve('f'=1/(2 * 'PI' * 'sqrt'('L' * 'C')), 'C')"`
but that gave a **wrong** answer
and I had to do 

`C:\Program Files (x86)\Qalculate>qalc -t "solve('f'=1/(2 * PI * sqrt('L' * 'C')), 'C')"`

so it seems that only user variables required single quotes.

**Comment by hanna-kn** [comment]
Quotes should only be used for unknown variables that is not pre-defined (as well as dates and text strings).
Since pi is defined I would instead do  `qalc -s "appr exact" -t "solve('f'=1/(2 * pi * sqrt('L' * 'C')), 'C')"`, although in this case the result will be the same.

> Do I need to install qalculate! on the target PC to use qalc? Or will the qalc.exe along with some dll's suffice?

The files in the definitions directory is also required for much functionality (units, most defined variables/constant, and many functions).

> it exists only in "C:\Program Files (x86)\Qalculate\definitions\variables.xml" => 35KB

The program seems to be aborted when writing functions.xml.

**Comment by GitterHubber** [comment]
> Since pi is defined I would instead do `qalc -s "appr exact" `

Ok Thanks!, Under what conditions is it necessary to use "appr exact"?

**Comment by GitterHubber** [comment]
Ok so `help set` gives me the required info but also throws in some wierd characters into the mix. I guess these characters will be decoded correctly and displayed in a Linux console but not so in Windows.

![image](https://user-images.githubusercontent.com/2816034/50294881-de26ba00-049c-11e9-9dc3-04ff84700414.png)

**Comment by hanna-kn** [comment]
> Ok so help set gives me the required info but also throws in some wierd characters into the mix. I guess these characters will be decoded correctly and displayed in a Linux console but not so in Windows.

The weird characters are escape sequences for text formatting (italicized, bold, underlined). It seems that it is possible to enable support for at least a subset of these in Windows 10.
