### ISSUE TITLE
Random numbers

### ISSUE THREAD

**Issue by meolic** [Qalculate/libqalculate#122]
Missing random number generator very much. Without it, not usable in my project - the same for bc and calc, only wcalc includes it. I hope, you can implement random numbers, because your other functions are really great!

**Comment by hanna-kn** [comment]
A random number generating function has been present since the first versions from 2004.

Use `rand` for a random floating point number between 0 and 1, or `rand(n)` for a random integer between 1 and _n_.

Is there some specific random number feature you're missing. (Perhaps an option to generate many numbers at the same time? This can currently be done by passing a vector to the rand() function, e.g. `rand(6,6,6,6,6,6)`, or using for example `genvector(rand(6);1;100;1;x;1)`, which will return a vector with 100 integers between 1 and 6, but could certainly be simplified.)
