### ISSUE TITLE
factorized result is wrong during equation solving

### ISSUE THREAD

**Issue by nick87720z** [Qalculate/libqalculate#131]
I just upgraded to fresh git code.
Input expression (using qalculate-gtk):
`
((0.299 · (1 − ((1 − n) · x))) + (0.587 · (1 − ((1 − y) · x))) + 0.114) = (0.587 + 0.299)
`

Output from log (taking by copying full text):
```
factorized result is wrong: 0.001x(587y − 587). This is a bug. Please report it.
factorized result is wrong: 0.001x(299n − 299). This is a bug. Please report it.
To avoid division by zero, the following must be true: n ≠ 1.

= (n = 1 and x = 886 ∕ (587 − 587y) and x ≥ 1 ∕ (1 − y) and y > 1)
or (n = 1 and x = 886 ∕ (587 − 587y) and x ≤ 1 ∕ (1 − y) and y < 1)
or (x = 886 ∕ (886 − 299n − 587y) and y = n and n > 1)
or (x = 886 ∕ (886 − 299n − 587y) and y = n and n < 1)
or (x = 886 ∕ (299 − 299n) and y = 1 and n > 1 and x ≥ 1 ∕ (1 − n))
or (x = 886 ∕ (299 − 299n) and y = 1 and n < 1 and x ≤ 1 ∕ (1 − n))
```
For meaning - i'm trying to get some formulas for certaing color correction.
n, y, z - map to R, G, B calues, while x - multiplier, which is supposed to be applied to inverted components (screening coefficients).

Just to note:
When i tried earlier without two restrictions at the end, and it gave me formula, whose output with same color resulted to R become negative (still not best, as i hope to get rather multiplication coefficient instead of screening).

Edit (another note):
I described my original equation: ((0.299 · (1 − ((1 − n) · x))) + (0.587 · (1 − ((1 − y) · x))) + 0.114) = (0.587 + 0.299)
But since it is going to make very low saturation for blue, i decided to look what will happen with target visual brightness = 0.114 :)

Edit2: I just saw, what siliness i did, setting weakest coefficient as target (must be at least strongest) - if it where multiplier coefficient, it should result to just 0.0, but for screening - result is rather unclear/undefined :D so, it is rather about error handling or like "No solutions" output.

Edit3: this should have some solutions:
`0.299 (1 − (1 − n)x) + 0.587 (1 − (1 − y)x) + 0.114 = 0.587 + 0.299 and 1 − (1 − n)x ≥ 0 and 1 − (1 − y)x ≥ 0`
But it still gives me this error.

**Comment by hanna-kn** [comment]
`((0.299 · (1 − ((1 − n) · x))) + (0.587 · (1 − ((1 − y) · x))) + 0.114) = (0.587 + 0.299)` returns the correct answer `x = 114 ∕ (886 − 299n − 587y) and y ≠ 886 ∕ 587 − (299 ∕ 587)n` without any errors or warnings. Adding `1 − (1 − n)x ≥ 0 and 1 − (1 − y)x ≥ 0` to the expression does however result in the "factorized result is wrong" error (this is usually completely harmless for the end user), but still seems to return a correct (although irritatingly long) answer.

It turned out to be a very simple issue. The not completely simplified polynomial "0.587xy - 0,886x + 0.299x" is factorized. The original value is then compared to the expanded and simplified factorized value "0.587xy - 0.587x" which is not strictly the same.
