### ISSUE TITLE
Inconsistent currency return values

### ISSUE THREAD

**Issue by dschopf** [Qalculate/libqalculate#144]
When querying print information for different currencies I noticed some inconsistencies.

- There is no way to get "USD", only either "dollar" or "$". I know that this is probably the only currency which can print the symbol in plain ASCII. However, it would be nice to be able to retrieve some kind of three letter abbreviation for all currencies.
- The currency "cent" is listed twice, is there any difference between them?
- The currencies "cent" and "eurocent" return empty strings for some calls of abbreviation(): (false, false) for both and (false, true) for "eurocent. It looks like there is no singular, but print for singular works.

Tested with the following code:
```
#include <iostream>
#include <memory>

#include <libqalculate/qalculate.h>

int main() {
  auto c = std::make_unique<Calculator>(new Calculator());
  c->loadExchangeRates();
  c->loadGlobalCurrencies();
  c->loadGlobalDefinitions();
  c->loadLocalDefinitions();
  c->fetchExchangeRates();

  for (auto &u : c->units) {
    if (u->isActive() && u->isCurrency()) {
      std::cout << "NEW CURRENCY : " << u->print(false, false, false) << "\n";
      std::cout << "\tprint: " << u->print(false, false, false) << " - " << u->print(true, false, false);
      std::cout << " - " << u->print(false, true, false) << " - " << u->print(false, false, true);
      std::cout << " - " << u->print(true, true, false) << " - " << u->print(true, false, true);
      std::cout << " - " << u->print(true, true, true) << "\n";
      std::cout << "\tabbrev: " << u->abbreviation(false, false) << " - " << u->abbreviation(true, false);
      std::cout << " - " << u->abbreviation(false, true) << " - " << u->abbreviation(true, true) << "\n";
    }
  }

  return 0;
}
```

**Comment by hanna-kn** [comment]
- u->referenceName() will always return the currency code.
- "cent" is only listed once for me. It should not be possible for two active currencies with the same name to exist. Can you please show the duplicate cent output you get?
- "cent" has a Unicode abbreviation which is returned using abbreviation(false/true, true). "eurocent" does not have any abbreviation at all (there are no official symbol) and therefore returns an empty string for abbreviation(false, false/true). The first argument specifies if the singular for should be returned if no abbreviation is available.
- You can use u->getName() to retrieve all names of each unit.
- c->loadGlobalCurrencies() is unnecessary (loadGlobalDefinitions() loads currencies) . I recommend that you call fetchExchangeRates() before loadExchangeRates() (in currencies in the exchange rates source has changed).

**Comment by dschopf** [comment]
> u->referenceName() will always return the currency code.

Yes, that seems to provide the strings I was looking for.

> "cent" is only listed once for me. It should not be possible for two active currencies with the same name to exist. Can you please show the duplicate cent output you get?

I can see it twice. However only when I call loadGlobalCurrencies before loadGlobalDefinitions. When I remove loadGlobalCurrencies the duplicate entry is gone. 

> "cent" has a Unicode abbreviation which is returned using abbreviation(false/true, true). "eurocent" does not have any abbreviation at all (there are no official symbol) and therefore returns an empty string for abbreviation(false, false/true). The first argument specifies if the singular form should be returned if no abbreviation is available.

For me the "cent" return values are still inconsistent:
```
   NEW CURRENCY : cent 
        print: cent - cents - cent - cent - cents - cents - ¢
        abbrev:  - cent - ¢ - ¢
```
u->print(false, true, false) returns "cent" but u->abbreviation(false, false) returns an empty string?
What does the short_ argument in print() actually do? Not the abbreviation?

> You can use u->getName() to retrieve all names of each unit.

Where can I get valid index values for the getName() function from? Do I have to iterate starting from 0 until it returns empty_expression_name?

> c->loadGlobalCurrencies() is unnecessary (loadGlobalDefinitions() loads currencies) . I recommend that you call fetchExchangeRates() before loadExchangeRates() (in case currencies in the exchange rates source has changed).

I have my own routine for fetching the exchange rates. So I was under the impression that calling loadExchangeRates() would reload the rates from the file. But reading the comment for loadExchangeRates() that does not seem to be the case. What do I have to call after downloading and replacing the exchange rates file? Or is it not possible to update the rates once the calculator has been initialized?

**Comment by hanna-kn** [comment]
> I can see it twice. However only when I call loadGlobalCurrencies before loadGlobalDefinitions. When I remove loadGlobalCurrencies the duplicate entry is gone.

I'll revise my previous statements: you should never ever call both loadGlobalCurrencies() and loadGlobalDefinitions().

> u->print(false, true, false) returns "cent" but u->abbreviation(false, false) returns an empty string?
What does the short_ argument in print() actually do? Not the abbreviation?

u->print() is primarily intended for "composite" units. For other units (including all currencies) this is just a wrapper for preferredName(), which has more detailed documentation. The function arguments specifies the preferred name format, but a non-empty name is always returned. If use_unicode is false, a name with ASCII characters will always be returned (if such exist) and thus overrides _short/abbreviation in this case. If the first argument of abbreviation() is false, an empty string may be returned.

> Where can I get valid index values for the getName() function from? Do I have to iterate starting from 0 until it returns empty_expression_name?

From the API documentation for ExpressionItem (parent of Unit):
"Returns name for an index (starting at one). All functions can be traversed by starting at index one and increasing the index until empty_expression_name is returned."

You can use `!getName(index).name.empty()` or `getName(index) != empty_expression_name`.

> I have my own routine for fetching the exchange rates. So I was under the impression that calling loadExchangeRates() would reload the rates from the file. But reading the comment for loadExchangeRates() that does not seem to be the case. What do I have to call after downloading and replacing the exchange rates file?

- loadBuiltinCurrencies() / loadBuiltinDefinitions() should be preceded by loadExchangeRates().
- loadExchangeRates() should be called after replacing the local exchange rates files. You can safely call loadExchangeRates() multiple times. Code for "exrates" command in qalc: `CALCULATOR->fetchExchangeRates(15); CALCULATOR->loadExchangeRates();`, followed by error check.
- if you use update the exchange rates during the initialization of the program you should ideally do it before loadExchangeRates() and loadBuiltinDefinitions(), otherwise you should call loadExchangeRates() twice.

**Comment by dschopf** [comment]
Thanks a lot for all the detailed explanations. I think I got my code now in such a state that it does the thing I expect it to do.
