### ISSUE TITLE
Feature request: AWG <--> metric 

### ISSUE THREAD

**Issue by Saboe** [Qalculate/libqalculate#164]
Most of the people in the world handle metric dimension units, so also I do, I'm metric. It would be nice if Qalculate! can calculate the diameter from AWG (American Wire Gauge) to metric units as diameter, or perhaps as cross section area and vice versa.

**Comment by hanna-kn** [comment]
This is easily implemented as a function (perhaps more appropriate than as a length/area unit?) with the expression `0.127mm*92^((36-x)/39)`. (You can add this function yourself using the <i>f(x)</i> button or File->New->Function (simplified) in the GUI, or the command `function awg 0.127mm*92^((36-\x)/39)` in qalc.)

**Comment by danieldjewell** [comment]
I just posted a comment on 55ace91 - I will post more shortly (I have a couple of other points I wanted to make), but I *think* the relation for circular mils (cmils) is wrong... see https://en.wikipedia.org/wiki/Circular_mil ... I believe 1cmil should be = (diameter)^2

https://github.com/Qalculate/libqalculate/blob/55ace91b6444fe513b3f1050ff9a6809af8fb6cd/data/units.xml.in#L1795

**Comment by danieldjewell** [comment]
Okay, had some time to dig in more on this. It's not entirely straightforward (gee, what a surprise with US units - this thing is much easier in metric. Fun fact: [had the prototype kilogram and metre made it to the USA from France in the late 1700s, we wouldn't have to have this conversation](https://www.nist.gov/blogs/taking-measure/pirates-caribbean-metric-edition)). 

So:

- The *"circular mil"* is defined as ```A = d^2``` - it disregards π. See https://en.wikipedia.org/wiki/Circular_mil
- The *"square mil"* is, just like the square mm or square inch: ```mil^2``` ... The *area* of a **wire** in square mils is the typical area of a circle equation: ```A = πr^2```. (But since 1 inch = 1000 mils ... 1 in² = 1'000'000 mil²...)
- For sure, the "circular mil" is not related to the *mil* by ```π/4``` ... it is, however, related to the square mil. See: https://en.wikipedia.org/wiki/Square_mil

I really don't know the best way to solve this. My personal preference would be to have AWG defined as a unit along with cmil, and the rest. The ideal situation in my mind would allow the following to be calculated in one line: 

- 10AWG to mm^2 (cross sectional area - as used in European wire sizes) 
- 10AWG to cmil 
- 10AWG to mil^2 (or sqmil) 
- 10AWG to mm (diameter)
- The reverse of all of the above 

I played around with the units a bit and had *some* success but something is off. See below. 

Part of the problem is that the units are a somewhat crazy mix of "length" and "area". I suppose part of that is that wire size in mm² is just that: True area. (i.e. πr²) However, circular mils *implies* that it's the area of a circle. (No π) There [*is* also a metric equivalent - ccm - circular centimetres](https://en.wikipedia.org/wiki/Circular_mil#Metric_equivalent). 

I think units are the best way to implement this (because they *are* distinct units) ... I just am not sure how best to relate them. 

```xml
   <unit type="alias">
      <system>US</system>
      <use_with_prefixes>false</use_with_prefixes>
      <title>American Wire Gauge</title>
      <names>r:AWG</names>
      <base>
        <unit>in</unit>
        <relation>0.005inch*(92^((36-\x)/39))</relation>
        <inverse_relation>-39*log(\x/0.005inch,92)+36</inverse_relation>
        <exponent>1</exponent>
      </base>
    </unit>
```

**Comment by hanna-kn** [comment]
From Wikipedia:
"A circular mil is a unit of area, equal to the area of a circle with a diameter of one mil"

The area of a circle with a diameter one mil (and thus one cmil) equals 
`pi*r^2=pi*(mil/2)^2=mil^2*pi/4`.

A=d^2 is the area of _a circle_ in cmil. E.g. if the diameter is 4 mils, the area of the circle is 16 cmils. If we convert this to mil^2 (using cmil=mil^2*pi/4), we get `16 cmils=16*(mil^2*pi/4)=4pi mil^2`.

Qalculate returns the following results when converting AWG (using the functions included in the latest version libqalculate):
```
awg(5) to mm^2 = 67.43
awg(5) to kcmil = 133.08
awg(5) to mm^2 = 16.77
awg(5) to kcmil = 33.10
```
According to Wikipedia, this is correct.

The area unit for AWG would be defined in relation to cmil using the expression 25*8464^((36-\x)/39). The main drawback of defining AWG as units instead of functions, is that you would be forced to use negative values for sizes larger than 0 (e.g. -3 instead of 0000 or 4/0). The units would not really be useful for anything other than direct conversion.

**Comment by danieldjewell** [comment]
> The area of a circle with a diameter one mil (and thus one cmil) equals
> `pi*r^2=pi*(mil/2)^2=mil^2*pi/4`.

I see what you're saying now - I think I was trying to look at it a different way and probably ended up getting distracted (that's also what I get for trying to work on something when I'm too tired :).) 

I definitely see now that **awgd()** is returning the diameter in mm (or another unit of *length*) and awg() is returning a unit of *area*. Which is also why ``` pi * ( ( awgd(10) / 2 )^2 )``` works and returns mm² (which can be converted to cmils....)

```
> pi*(awgd(10)/2)^2
  pi * ((awgd("10") / 2)^2) = approx. 5.2611550 mm^2
> to cmil
  5.2611550 mm^2 = approx. 10383.022 cmils
```

I was trying to find a way to unify the conversion so that there wasn't a need for two functions... Although I'm not sure if that would be good. 

I just thought through it again and although it might be possible to apply a formula to convert to circular mils from a unit of length, if it was done as a unit, there would be no way to know whether the input unit (which would be a length) would be the *diameter* or the *radius*. The code would have to pick one or the other which could be very unpredictable from a user's perspective. 

Nevermind - I was trying to make something simpler and ended up making it more complex 🙃. (It would indeed be way easier if we just all used metric... 👍) Sorry for the confusion!
