### ISSUE TITLE
Currency rates for Belarus ruble (and other currencies?)

### ISSUE THREAD

**Issue by notpushkin** [Qalculate/libqalculate#172]
I see that the Belarus Ruble rate is defined in https://github.com/Qalculate/libqalculate/blob/e31b1d567fefd7d23aed08948f26e821fe14615b/data/rates.json (`{"currency_code":"BYR","rate":19600,"code":"BY","name":"Belarus"}`), however a lot of time has passed since it was updated (even a denomination occured!), and currently it's 2.1098 BYN/USD. Probably we can just hardcode it as an inexact rate, but maybe we could do more than that and add support for different exchange rate backends? (E. g. for Belarus it would be http://www.nbrb.by/services/xmlexrates.aspx)

**Comment by hanna-kn** [comment]
It is a known issue that a few currencies (BYR, MRO, VES, ZMK) in Qalculate are obsolete, and that the replacement currencies are missing (BYN, MRU, VEF, ZMW). These are marked as obsolete in the unit titles (e.g. "Belarusian Ruble p. (obsolete)").

If you can confirm that https://www.nbrb.by/services/xmlexrates.aspx is reliable and can be used freely, I will add it to libqalculate as an exchange rate source.

**Comment by notpushkin** [comment]
I've looked more into it and it seems that XML-based service is deprecated now (although no plans to turn it off have been announced)It is recommended to use JSON-based endpoints instead (docs [in Russian](https://www.nbrb.by/APIHelp/ExRates), [Google Translate](https://translate.google.com/translate?sl=ru&tl=en&u=https%3A%2F%2Fwww.nbrb.by%2FAPIHelp%2FExRates)). The JSON endpoint to get the BYN/USD rate is: http://www.nbrb.by/api/exrates/rates/usd?parammode=2

I couldn't actually find any ToS or uptime info on the site, but this is the official service of the Belarus National Bank so it should be fairly reliable in my opinion. If you do have any sort of concerns though, I can drop an email to them :)

**Comment by hanna-kn** [comment]
Done.

I choose to use the BYN/EUR rate, since the data from the European Central Bank is most reliable (and is always retrieved quickly) and provides exchange rates for all the major currencies. Ideally the nbrb.by data for every currency would be used when converting BYN, in order to avoid reduced precision because of the likely different update times of the sources, but the resulting error should be small and largely irrelevant in the context (I expect currency speculators to use other tools).

Unfortunately the https version of the url seems unreliable.
