### ISSUE TITLE
inconsistent unicode exponents

### ISSUE THREAD

**Issue by nycex** [Qalculate/libqalculate#201]
Currently, with unicode mode enabled, qalc uses unicode exponents only for units and only the characters `²` and `³` . Potentially every integer number could be displayed as unicode with the characters  `⁻¹²³⁴⁵⁶⁷⁸⁹⁰` and even other expressions with e.g. `⁺⁽⁾`. 
And as already said, for something like unknowns, superscript numbers aren't used at all. 
And lastly, the `⁻` character isn't even recognized in the input expression.

Preview:
![preview](https://user-images.githubusercontent.com/24685286/83295328-116f8b80-a1ef-11ea-8cd1-7687a78d00cf.png)

**Comment by hanna-kn** [comment]
1, 2 and 3 are the most common Unicode superscripts available in fonts (these are the only characters visible when viewing this issue on Android). When the character is not available in the current font, the appearance is inconsistent (as is the case with the minus superscript in the screenshot). Since exponents other than 2 and 3 are unusual with units this is mainly an issue when negative exponents are enabled.

Another issue with Unicode superscripts is that they are usually very small and thereby hard to read. For this and for consistency reason I'm considering removing all superscripts from the output.

I will add support for minus and parentheses superscripts in input tomorrow.

**Comment by hanna-kn** [comment]
Support for plus, minus, and parentheses superscripts is now finished.

Combining superscripts is problematic when using monospaced fonts (which I assume is used with qalc), since there will be too much spacing between the characters.
