### ISSUE TITLE
disk/network storage unit: MB = 1024 KB and Mb = 1000 Kb

### ISSUE THREAD

**Issue by amosbird** [Qalculate/libqalculate#221]
Hello! How can I setup KB, MB, GB, TB ... and Kb, Mb, Gb, Tb units in libqalculate?

**Comment by hanna-kn** [comment]
Upper-case B will likely be used as abbreviation for byte instead of bel (seldom used without deci prefix) in the next version of libqalculate.

I advice you to learn the correct decimal and binary prefixes (e.g. kB = kilobyte = 1000 B, KiB = kibibyte = 1024 B, MB = megabyte = 1000 kB, MiB = mebibyte = 1024 KiB). 

Lower-case b is used as abbreviation for the unit barn and is in other contexts sometimes used for bits, and is therefore not deemed appropriate as abbreviation for byte.

**Comment by amosbird** [comment]
> I advice you to learn the correct decimal and binary prefixes

Thanks!

**Comment by amosbird** [comment]
Hmm, actually what I need is not a unit but a scale.... Can we have ` 10 Gi` expanded to `10737418240` without unit? And others
```
10 Ki -> 10240
10 Mi -> 10485760
10 K -> 10000
10 M -> 10000000
...
```

**Comment by foreachthing** [comment]
10 Gi are 10, without units... you need a unit to know what to convert it to, no!? Why not type 10 Gi to bytes? What's wrong with that?

**Comment by amosbird** [comment]
@foreachthing it's for number transformation so I don't need to manually type `10 * 1024 * 1024 * 1024`.

**Comment by hanna-kn** [comment]
The main issue with allowing prefixes without units is that some of them conflict with other objects (e.g. m = meter, T = tesla, G = gravitational constant). Upper-case K is not a recognized prefix (it would nevertheless conflict with kelvin).

> it's for number transformation so I don't need to manually type 10 * 1024 * 1024 * 1024.

What kind of number transformation?

`10 * 2^30` is easier to type (Ki = 2^10, Mi = 2^20, Gi = 2^30, etc.).
It is also possible to use `10 * GiB / B` or similar.

**Comment by amosbird** [comment]
> It is also possible to use 10 * GiB / B or similar.

Ah, that would be the way to go. Thanks!
