### ISSUE TITLE
Add rank function for matrix

### ISSUE THREAD

**Issue by RustemB** [Qalculate/libqalculate#231]
Here is rank function only for vectors, but not for matrix

**Comment by hanna-kn** [comment]
What do you expect the rank function to do with matrices? The rank of a matrix is normally defined as something quite different (related to linear algebra instead of statistics) from what the rank function does in Qalculate.

I will add support for statistical ranking of matrices in the rank function.

**Comment by RustemB** [comment]
For example rank of matrix
```
5 6
1 0
```
is 2, because `det` of this matrix is not 0

**Comment by hanna-kn** [comment]
Done. Matrix rank function has now been added as rk() and will be included in version 3.14.0 (2020-10-26).
