### ISSUE TITLE
Your autogen.sh uses libtool instead of libtoolize

### ISSUE THREAD

**Issue by sebma** [Qalculate/libqalculate#30]
Hi,

I'm using Debian 8 and it seems your `autogen.sh` uses `libtool` instead of `libtoolize`.

Can you please replace `libtool` with `libtoolize` at line 34 of `autogen.sh` ?

Thank you for your comprehension.

**Comment by hanna-kn** [comment]
The libtool binary are available in the libtool-bin package on Debian. 

I'm not really sure if libtool can be replaced with intltoolize without any other changes.

**Comment by sebma** [comment]
I'm not talkink about `intltoolize` but **`libtoolize`**

BTW: the `libtool-bin` package is not available before Ubuntu 16.04 : 
```
$ apt-cache show libtool-bin
N: Can't select versions from package 'libtool-bin' as it is purely virtual
N: No packages found
```

**Comment by sebma** [comment]
I'm not talking about `intltoolize` but **`libtoolize`**

On Debian Stable at the University, I don't have the admin rights so I cannot install any package.

They just have `libtoolize` from the debian `libtool` package.

I did modify your `autogen.sh` file locally and it seems to work with `libtoolize` except I have the fooling error : 
```
make[3]: *** No rule to make target '../../docs/reference/html/*.png', needed by 'all-am'. Arrêt.
make[3]: Leaving directory '/cal/homes/mansfeld/src/libqalculate/docs/reference'
Makefile:387: recipe for target 'all-recursive' failed

```

BTW: The Class Library for Numbers autoreconf uses libtoolize :)

**Comment by hanna-kn** [comment]
If you use the official source source tarball for the latest version (https://github.com/Qalculate/libqalculate/releases/download/v0.9.11/libqalculate-0.9.11.tar.gz), instead of the git version, than you should usually not need to run autogen.sh at all.

The error you probably get because doxygen, which is used for generation of API reference documentation (but not needed with the release tarball), is missing.

"intltoolize" was a typo.

I do however now notice that it is libtoolize, and not the libtool binary, that is actually used in autogen.sh and I will therefore change autogen.sh so that it instead tests if libtoolize is available.
