### ISSUE TITLE
libqalculate doesn't gracefully handle mistakenly using a unit of temperature in a hexadecimal expression

### ISSUE THREAD

**Issue by Pointedstick** [Qalculate/libqalculate#36]
People often try to mistakenly input hexadecimal numbers as F2 or 1C (instead of 0xF2 or 0x1C). When they do this, libqualculate produces undefined behavior, which can crash software that uses libqalculate.

You can see this by using KDE KRunner (which uses libqalculate as a backend) and entering either of the following:
- =(1C)^2
- =F2

KRunner crashes in response to the undefined output.

This was discovered in https://bugs.kde.org/show_bug.cgi?id=358617

**Comment by hanna-kn** [comment]
I can see any reasonable way for libqalculate to determine when the user is expecting a hexadecimal instead of a unit (coulomb and farad) in the above examples, when the user is not using the 0xF2 notation or the hex() function (`hex F2`).

libqalculate should of course not crash, but unfortunately that was obviously the case with the old 0.9.7 version.
