### ISSUE TITLE
Support number suffix `M`, not just `k`

### ISSUE THREAD

**Issue by h-h-h-h** [Qalculate/libqalculate#376]
When I, e.g., write `2.5k`, this outputs `2 500`. But when I write `2.5M`, even though, when typing `M`, Qalculate suggests "mega M &#xa0; Prefix: 10^6", it outputs `2.5`, not `2 500 000`.

Please support the `M` suffix also (just *uppercase M*).

Since Qalculate already interprets `B` as "byte", I suppose there is no way of interpreting it as "billion" or "10^9".

**Comment by hanna-kn** [comment]
Prefixes should, ideally, never be used without a unit. I've however made an exception for non-abbreviated prefixes because there are few potential conflicts. I've also, reluctantly, made an exception for lower-case _k_ (as an abbreviation when preceded by a number).

The usage of _M_ as abbreviation for million might also be common enough (although I'm not sure if lower-case _m_ is more common, and the potential for misinterpretations are greater) to motivate another exception. I would however recommend that you use 1E6 (scientific E notation) as short for million instead (e.g. 2.5E6).

Abbreviations and standalone prefixes are not really possible for larger (or smaller) numbers (e.g. G = gravitational constant, T = Testla, c = speed of light, etc.).
