### ISSUE TITLE
Crash in Calculator constructor on strdup

### ISSUE THREAD

**Issue by kbroulik** [Qalculate/libqalculate#4]
I got this downstream KDE bugreport in the KRunner ("Run Command") calculator plugin which uses libqalculate: https://bugs.kde.org/show_bug.cgi?id=365117

**Comment by hanna-kn** [comment]
I am not able to reproduce the crash using the latest arch packages.

**Comment by hanscomps** [comment]
Interesting.  Having the same problem.  Arch fully updated.  Pulled libqalculate source and compiled separately.  Same issue, crash when executing "qalc".

**Comment by hanna-kn** [comment]
Does it still crash if you run `LC_ALL=C qalc`

**Comment by saidinesh5** [comment]
@hanna-kn  https://github.com/Qalculate/libqalculate/commit/eade7b723a81b4d4b2039da1ed91bac2a5795805#diff-2920795eb5a84823e79c2cfaf6fd7d71R299 commit fixed it for me i think....

**Comment by hanscomps** [comment]
Fixed, thanks

**Comment by hanna-kn** [comment]
The cause of this problem is that the locale (specifically LC_NUMERIC) is incorrectly set on the users system. With the commit mentioned above this does not cause a crash with Qalculate! anymore, but the user (or KDE) should still make sure that the system locale is correctly set (or at least is left empty).
