### ISSUE TITLE
Length unit conversion

### ISSUE THREAD

**Issue by crides** [Qalculate/libqalculate#417]
On `qalc 4.1.0`

When doing `m^-1 to mm` it returns `meter^−1 = 1000 mm` which is obviously wrong. Discovered this when converting inches to mm, such as `3/4" to mm` returns `3 / (4 × inch) ≈ 33.86666667 mm` which is wrong both numerically and in units; numerically this is equal to `4 * 25.4 / 3`, while the actual answer should be `19.05mm`

**Comment by hanna-kn** [comment]
This is what happens: 3/4" = 3/(4 in) ≈ 0.030/mm, calculate the reciprocal to get mm => 1/(0.030/mm) ≈ 33 mm. The reasoning behind this should be more clear if compared with an expression such as "2 L/km to mpg" (returns 1.18 mpg instead of 0.85/mpg).

I've now restricted the use of the reciprocal in conversion to cases where to the specified unit to convert to has both negative and positive exponents, or only a single negative exponent.
