### ISSUE TITLE
How to detect errors when evaluating expression

### ISSUE THREAD

**Issue by alex1701c** [Qalculate/libqalculate#442]
In https://invent.kde.org/plasma/plasma-workspace/-/blob/master/runners/calculator/qalculate_engine.cpp#L68 I want to check if the Qalcuate evaluation contains an error.

An example where I want to identify an error is for queries like ` GNUPGHOME=`. See https://bugs.kde.org/show_bug.cgi?id=454132 for details.  Thanks in advance :)

**Comment by hanna-kn** [comment]
Either use `Calculator::message()` and `Calculator::nextMessage()`, or `Calculator::beginTemporaryStopMessages()` and `Calculator::endTemporaryStopMessages()`.

endTemporaryStopMessages() returns the number of blocked error messages.

message() returns the first CalculatorMessage object in the message queue. Check the type of the object (MESSAGE_INFORMATION, MESSAGE_WARNING, or MESSAGE_ERROR) using the type() member function (e.g. `CALCULATOR->message()->type()`). nextMessage() returns the next object in the queue and removes the first object from the top of the queue. You will need to iterate through all messages (until nextMessage() is NULL), or clear the queue using `Calculator::clearMessages()` before/after each subsequent calculation.

You should take a look at the code of the Qalculate Gnome shell search provider (https://github.com/Qalculate/qalculate-gtk/blob/master/src/searchprovider.cc).

The search provider uses the following function to check for errors:
```
bool has_error() {
	while(CALCULATOR->message()) {
		if(CALCULATOR->message()->type() == MESSAGE_ERROR) {
			CALCULATOR->clearMessages();
			return true;
		}
		CALCULATOR->nextMessage();
	}
	return false;
}
```

In addition the following code is used to validate the expression before any evaluation is performed:
```
bool b_valid = false;
if(!b_valid) b_valid = (expression.find_first_of(OPERATORS NUMBERS PARENTHESISS) != string::npos);
if(!b_valid) b_valid = CALCULATOR->hasToExpression(expression, false, search_eo);
if(!b_valid) {
	string str = expression;
	CALCULATOR->parseSigns(str);
	b_valid = (str.find_first_of(OPERATORS NUMBERS PARENTHESISS) != string::npos);
	if(!b_valid) {
		size_t i = str.find_first_of(SPACES);
		MathStructure m;
		if(i != string::npos) {
			str = str.substr(0, i);
			b_valid = (str == "factor" || equalsIgnoreCase(str, "factorize") || equalsIgnoreCase(str, _("factorize")) || equalsIgnoreCase(str, "expand") || equalsIgnoreCase(str, _("expand")));
		}
		if(!b_valid) {
			CALCULATOR->parse(&m, str, search_eo.parse_options);
			if(!has_error() && (m.isUnit() || m.isFunction() || (m.isVariable() && (i != string::npos || m.variable()->isKnown())))) b_valid = true;
		}
	}
}
if(!b_valid) return;
```

Also note that `Calculator::calculateAndPrint()` is used instead of separate calculate(), format(), and print() calls. This enables, among other things, further conversion options (e.g. `52 to hex`), and automatic setting of approximation and fraction modes. In the search provider a time limit of 100 ms is specified.

**Comment by alex1701c** [comment]
Thanks for the great explanation & code snippets. I will try to implement it this weekend.

**Comment by alex1701c** [comment]
The solution you provided works, thanks a lot!
