### ISSUE TITLE
Questions about precision.

### ISSUE THREAD

**Issue by AESisverystrong** [Qalculate/libqalculate#450]
On the 64-bit CLI, I tested that the maximum precision setting is only 646442893, which is not "arbitrary precision" (I know it's a bit of a stretch, 600 million is more than enough, and the memory required is usually not affordable). In the GTK graphics program, the maximum is only 100000, and QT is even worse, only 10000 (this is less, right?).
In the CLI, an error is reported when setting the precision over 646442893: 

> **_"... /... /mpfr-4.1.0/src/set_dfl_prec.c:32: MPFR assertion failed: ((prec) >= 1 && (prec) <= ((mpfr_prec_t) ((((mpfr_uprec_t) -1) >> 1) - 256))) "_**

Is this the maximum precision limit, please?

Also when using GTK, I am computing a nonlinear iterative equation and when computing it multiple times, the CPU and memory spent on the computation is very large. I suspect it's the internal precision, I don't need that much internal precision, but it's getting bigger and bigger. I can't set the internal precision here, at least I can't. Is it possible to change or limit the internal precision? (Seems like I should go to GTK and ask a question...But the CLI has this problem too, it's just that GTK's is more obvious)

I used the translator and I hope I won't make any errors.

**Comment by hanna-kn** [comment]
> I calculate this equation: 4Ans-4Ans^2 (which is actually a deformation of the logistic mapping)
After setting the precision to 10 and Ans to 0.23232323, I repeatedly calculate this equation.
At the beginning there was no problem, the calculation was fast. But when the calculation reached 18 times, it started to become slow, and after that it became slower and slower.

After 23 iterations the result is a rational number with numerator 2.189 554 406 × 10^62058419 and denominator approximately 2.199 511 897 × 10^62058419. If the initial value is set to 0.23232323±1e-50 or similar, the slowdown will not occur. This has now been fixed (the number will be converted to floating point before squaring if it has at least 500 000 digits).

> Other than that, do you plan to change the int type to arbitrary precision? I know it doesn't seem to be useful. Because there is not enough memory.

The issue not primarily lack of memory, but speed/time requirements. MPFR does not support setting precision higher than allowed by long type, which does not differ from int on Windows.

Note that the precision in MPFR is set in bits, while precision in Qalculate is the number of decimal digits. The internal MPFR precision is set to `precision × 3.322 + 100` bits (646 442 893 × 3.322 + 100 ≈ 2 147 483 391).

**Comment by hanna-kn** [comment]
> After more than 140 iterations, the accuracy is greatly corrupted and the result becomes something like: "interval(-465 941 474 509, 465 941 474 511)".
Adding uncertainty creates propagation, which then becomes interval arithmetic...

For increasing number of operations you will need to increase the precision (both the general precision, and, if you using the workaround, the specified uncertainty of the initial value). For 1000 iterations (I'm using optimized for() function to calculate this), a precision of 740 is required for 10 significant digits.

> It should not be possible to be slower than JAVA's BigDecimal, because this is at least C++.
But I tested to calculate 2 500 000 digits of Pi.
Qalculate! took about 1 minute and 36 seconds to complete the calculation on my computer.

I discovered that much of the slowness was caused by calls mpfr_log and mpfr_log10 (for determining precision from interval, and output). Replacing these with a function using mpz_sizeinbase (https://github.com/Qalculate/libqalculate/commit/e413a1464a280f10c76c7bf398b18005e4744bcf), I've managed to reduce the time to 5 seconds (or 3 s if only 10 digits are shown), and 83 s for 25 000 000 digits (or 49 s without full output).

> And what is the floating point overflow error (when calculating very large numbers). Because very large integers are converted to floating point numbers, but overflow is caused by the precision limit of MPFR?

By default the largest exponent (base 2) allowed for MPFR is 1 073 741 823 (regardless of precision). Qalculate does not change this.

**Comment by hanna-kn** [comment]
> Mainly when I calculate 25 000 000 bits of Pi, an error appears: "The calculation has been forcibly terminated. Please restart the application and report this as a bug. " (automatically occurring)

On Windows calculations, in qalc, are by default automatically terminated after 100 seconds (because termination on user input does not work on Windows). Qalculate then waits 5 seconds for the calculation to terminate at safe point (which is not reached because of the time spent in MPFR functions when precision is that high), otherwise the calculation thread will be forcibly terminated. The time, in milliseconds, allowed for for calculations can be changed using the -m/-time command line option (e.g. `qalc -m 3600000` for one hour).

> And I found that it seems that arbitrary precision arithmetic libraries use a restricted number to indicate the precision when calculating. Is this necessary? Is it because using arbitrary precision to represent accuracy in computation requires complex processing, its complexity and expense is so large that its useless, or is it simply impossible to use it to representation?

I'm not sure what you mean by this.

**Comment by hanna-kn** [comment]
> I find that almost all arbitrary precision calculations are finite. This is because they use an imprecise type to represent "precision" (e.g. double type for y-cruncher and int type for MPFR). Is it because precision can only be represented by ordinary types? Or is it because it's too hard to develop it?

Any higher precision would simply not be usable or meaningful.

The problem with MPFR is mainly that an integer type with different size on different platforms is used. On GNU/Linux the maximum precision value is as I've mentioned before 9 × 10<sup>18</sup> (compare this with the record for number of digits calculated of pi, 6.3 × 10<sup>13</sup>).

**Comment by hanna-kn** [comment]
> Is it not possible to have higher precision on Windows? Is it because it's too much trouble?

I assume that it would have been relatively easy to use long long (always at least 64 bit) instead of long in MPFR. I'm however not in any way involved in the development of MPFR and for Qalculate a higher precision limit would not really be meaningful. (Also, I'm not aware of MPFR being used for any record breaking attempts, and I assume Windows would not be used for any such purposes.)

> And is it algorithmically possible to represent precision with arbitrary precision types?

I see no reason why it would not be possible to use for example mpz_t instead in MPFR. It would however probably be easier to use an 128-bit integer (3.4 × 10<sup>38</sup>) instead. 

As I understand it y-cruncher is not similarly limited by the type representing the precision (the highest real value of double is 1.7 × 10^308), but other factors related to how the algorithms are implemented.

From http://www.numberworld.org/y-cruncher/algorithms.html:
> It is worth mentioning that the float-indexing limit is the only thing left that prevents y-cruncher from going all the way up to the 64-bit limit. Without it, it should be possible to reach 6.1 * 10<sup>17</sup> decimal digits (the limit of the Small Primes NTT).
> 
> Getting rid of the float-indexing limit will require a floating-point type with at least a 64-bit mantissa. A viable option is to use 80-bit extended-precision via the x87 FPU although some compilers don't support it. But since "float indexing" isn't exactly a performance bottleneck, any sort of software emulation will probably work as well.
