### ISSUE TITLE
Calculation error: sqrt(hbar c/G) - PlanckMass ≈ -666μg

### ISSUE THREAD

**Issue by delvydo** [Qalculate/libqalculate#476]
While playing around I found this calculation error.
The result should be 0.000 00±0.000 50 μg. It gives −666.4846±0.0075 μg instead.
Also reproducible in qalculate-qt. I'm not sure why it's doing that.
![image](https://user-images.githubusercontent.com/30949472/195705872-0fe0935b-bed2-404b-937e-c9a193368185.png)

**Comment by hanna-kn** [comment]
Fixed.

With interval calculation set to interval arithmetic, kilo prefix was wrongly replaced before removal of units from the relation to the base unit of PlanckMass.

The calculation of the expression is still not optimal since the correlation between the uncertainty of unit relation and the uncertainty of the physical constants is lost, which means that the precision of the result is reduced (0.0±4.9E-4 μg is returned instead of exactly 0 μg).
