### ISSUE TITLE
Unit conversion/resolution introduces additional incorrect units 

### ISSUE THREAD

**Issue by varuld** [Qalculate/libqalculate#498]
Unit conversion of "m/s^n" with n<=3 results in the wrong additional units. 

Exp:
✅ `qalc "m/s^2" => m/s^2`
❌ `qalc "m/s^3" => mHz·N/g`  - should be `m/s^3`
❌ `qalc "m/s^5" => mHz·N/(g·s^2)`  - should be `m/s^5`
❌ `qalc "m/s^6" => mHz·N/(g·s^3)`  - should be `m/s^6`
etc.

This issue is present in both qalc version 4.3.0 and current (time of writing) git version

**Comment by hanna-kn** [comment]
I wouldn't say that the units that the units are _wrong_ (`mHz·N/(g·s^3)` equals `m/s^6`), but unexpected and perhaps inappropriate. With automatic optimal unit conversion activated (default), Qalculate tries to return units with as low total exponent as possible. If this does not produce the desired units you will have to specify those manually (e.g. `qalc "m/s^6 to m/s^6"`, `qalc "m/s^6 to s"`, or `qalc "m/s^6 to base"`), or disable automatic unit conversion.

**Comment by varuld** [comment]
Just for clarification, I assume that the `g` of `mHz·N/(g·s^3)` represents grams i.e. `kg * 10^-3` , in `mHz·N/(g·s^3)` => `m/s^6` ?

If that is the case, I think that it is unclear and unintuitive to use `g` to represent mass, my presumption was that it represented standard gravity `(g=9.8 m/s^2)`.

**Comment by hanna-kn** [comment]
Standard gravity is denoted by g<sub>0</sub> (or ɡ<sub>0</sub> or ɡ<sub>n</sub>). I think it would be odd to not use g as symbol for gram in a general purpose calculator, and it would be confusing for the meaning of g in kg to change when used without prefix.

I was not aware before that m/s³, m/s⁴, m/s⁵, and m/s⁶ were used in any context. Automatic conversion can be fixed by adding these as derived units (as has now been done).

**Comment by varuld** [comment]
> it would be odd to not use g as symbol for gram in a general purpose calculator

In that context you're right, however I didn't know the g₀ notation before raising the issue, ergo my confusion.


Thanks for the help.
