### ISSUE TITLE
Compute on date/time

### ISSUE THREAD

**Issue by fcoiffie** [Qalculate/libqalculate#5]
Is there a way to compute some operations with date/time (like addition/substraction) ? Like 13h56min12s-1h25min to s ?

**Comment by hanna-kn** [comment]
To calculate your example, type "13h+56min+12s−(1h+25min) to s" or "13:56:12h−1:25h to s".

For date arithmetics you need to use functions (for example `days()`, which returns the number of days between two dates, and `addTime()`).

**Comment by fcoiffie** [comment]
And is there a way to get a result in "xx h xx min xx s" ?

**Comment by hanna-kn** [comment]
If you use time format as "number base" (in qalc: `set base time`), "5h+2min+3s to h" (or "18123 s to h") returns the result 5:02:03 h. 

It should however be possible for me to make it simpler for the user by adding the possibility to convert time units (as well as for example imperial length units) to predefined sets of multiple units (perhaps so that "18123 s to time" returns "5 h + 2 min + 3 s", or at least "5:02:03 h"). I will add it to the to-do list.

**Comment by fcoiffie** [comment]
Ok, thank you very much ! (I think, the same thing could be done for degrees, minutes, seconds)

**Comment by hanna-kn** [comment]
Support for "mixed" units conversion has now added. "13h+56min+12s−(1h+25min)" will now return "12 h + 31 min + 12 s". The support for mixed units works for all units, and is activated by default for time units and some imperial and U.S. customary units. This is controlled by the "autoconversion" setting in qalc, and can be fully enabled (forced)/disabled in unit conversion by appending unit expression with '+' or '-' ("to mixed" can also be used).

**Comment by protist** [comment]
I actually came here searching for the same thing, specifically how to output in time format, i.e. with `set base time`. I had a lot of trouble finding this information anywhere. It wasn't in `qalc --help`, nor `man qalc`, and I couldn't find it in the [online manual](https://qalculate.github.io/manual/index.html), which seems to be mainly about the GUI version? Is there somewhere to find more detailed information about the CLI qalc?

**Comment by hanna-kn** [comment]
> I actually came here searching for the same thing, specifically how to output in time format, i.e. with `set base time`.

The same as `set base time` can be achieved using `to time`, either at the end of the expression or as a separate command.

If you want to combine time format with time units, the best alternative is to divide the whole expression by hours, h (I have now made changes so that this will be done automatically when using time format). You can achieve a similar result by converting the result to hours and disabling mixed units conversion, using `to -h`.

> I had a lot of trouble finding this information anywhere. It wasn't in `qalc --help`, nor `man qalc`, and I couldn't find it in the [online manual](https://qalculate.github.io/manual/index.html), which seems to be mainly about the GUI version? Is there somewhere to find more detailed information about the CLI qalc?

Type `help` or `help COMMAND` (e.g. `help to`) in qalc.

Relevant information is also available in the [Expressions](https://qalculate.github.io/manual/qalculate-expressions.html) chapter (the [The “to” (and “where”) operators](https://qalculate.github.io/manual/qalculate-expressions.html#qalculate-to) section) of the GUI manual.

**Comment by protist** [comment]
Brilliant! Thanks @hanna-kn. That answers all my questions.

**Comment by sergeevabc** [comment]
Is there a way to compute how many (…) passed between two timestamps? Something like `qalc today 11-04-2021`.

**Comment by hanna-kn** [comment]
`"2021-11-04" - today` or `days(today, 2021−11−04)`

**Comment by sergeevabc** [comment]
@hanna-kn, it does not work as expected, alas. E.g. Google [says][1] 12 days passed between today and 11-04-2021, but…
```
$ qalc "2021-11-04" - today
2021 - 4 - 11 - today = 2006 - "2021-04-23"

$ qalc days(today, 2021−11−04)
days("2021-04-23"; "2021-11-04") = 195
```

[1]: https://www.google.com/search?hl=en&q=days+passed+between+today+and+11-04-2021

**Comment by hanna-kn** [comment]
@sergeevabc
- 11 April 2021 should be "2021-04-11" in standard date form (some other local date formats are also be supported).
- Quotation marks are usually removed from command line arguments (by the shell)

You should thus use `qalc "today - '2021-04-11'"` or `qalc "days(today, 2021-04-11)"` (unquoted parentheses usually results in syntax error).

**Comment by sergeevabc** [comment]
@hanna-kn, it works now, but those double quotes vs single quotes vs single double-quoted quotes are not intuitive. :(

**Comment by hanna-kn** [comment]
@sergeevabc

If you calculate an expression directly on the command line and some characters confuses or are removed by the shell, you need to put the expression in quotes (single or double quotes). If the expression contains quotation marks, a different kind of quotation marks must be used for the whole expression (e.g. `qalc 'today - "2021-04-11" + 2 days'`). It is also possible to only put the date within in extra quotation marks, or escape the quotation marks (e.g. `qalc today - \"2021-04-11\"`). Alternatively you can use the date function (e.g. `qalc "today - date(2021, 04, 11)"`).

If you run qalc in "interactive" mode (without any expression), you do not need to bother with any of this.

**Comment by sergeevabc** [comment]
Thank you for such a verbose reply, Hanna. Alas, I never use interactive mode, and the rest looks complicated to remember. I know paths with spaces should be double quoted to be processed correctly and usually that’s enough to work with FFMPEG, Imagemagick, Ripgrep, Lame, 7-zip, Curl, and other popular CLI apps. Good news is that I found [Datesum][1], a simple app for this task.
``` console
$ datesum today 2021-04-11
12 days
```

[1]: https://bytepointer.com/tools/index.htm#datesum

**Comment by sergeevabc** [comment]
@hanna-kn
`days(2022-12-06; 2021-04-11)` works (=604)
`days("2022-12-06", "2021-04-11")` does not work :(
Perhaps that guessing algorithm should be refined a bit.
