### ISSUE TITLE
Proposal for uncertainty propagation feature

### ISSUE THREAD

**Issue by mattmrnt** [Qalculate/libqalculate#50]
The main feature i notice missing in this very useful, expansive tool is the inclusion of uncertainties, which would extend the usefulness of this calculator into territory that it seems very few have tread previously. The inclusion of uncertainty propagation would allow qalculate to be used in a wider range of problems that specifically focus on "real" data where uncertainties are always present. The only other tool i've found that deals with associated uncertainties transparently and correctly is actually a python library which is likely worth looking at for implementation details here: https://pythonhosted.org/uncertainties/

There are several worthwhile syntax choices to choose from, a simple "number+-error" could be used or a new error(value,error,errortype) function or similar could be used to tell qalculate when a value with an error is being considered. Values with errors would then need to be propagated through error propagation rules, and recognize when the same variable is being used to correctly differentiate between the math for dependent and independent errors.

**Comment by hanna-kn** [comment]
The currently developed version supports some of the functionality of the uncertainties python package. 

Expressions such as sin(1.5+/−0.1) (= 0,99272486±0,00727514) are supported for almost all functionality (except some equations). 

libqalculate does however use interval arithmetics to achieve this and will give slightly different results compared to the uncertainties python package (mainly because the mid value of the result, instead of the result for the mid value, is displayed before ±). It is still possible that I will add support for proper statistical error propagation calculation in the future and more work is needed for dependent intervals/errors (3x-x, x^2/x, x^2-x, x(x-y) and similar are currently handled correctly, but not for example expressions involving trigonometric functions).

In addition there is an interval() function, and the result can be displayed using significant digits or as an interval. If interval arithmetics mode is activated, an interval is calculated for all floating point calculations and intervals/uncertainties can be created automatically with the read precision option (3.0 is interpreted as 3.0±0.05). Uncertainties are defined for all physical variables.

**Comment by hanna-kn** [comment]
Interval arithmetic has been improved and now returns the (reasonably) precise interval for most functions/expressions that are differentiable and continuous within the interval (even if it oscillates).

For small uncertainties Qalculate! will normally return very similar results compared to the python library. For large errors Qalculate! will return a value that might be considered to be more accurate (but an option to display the result for the original mid value might be beneficial).
