### ISSUE TITLE
exrates fetches 502 Bad Gateway from mycurrency.net

### ISSUE THREAD

**Issue by arcxio** [Qalculate/libqalculate#500]
This is what exrates downloads into ~/.local/share/qalculate/rates.html:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Thus making pairs from mycurrency.net unusable.
But when I fetch it manually with `curl -o ~/.local/share/qalculate/rates.html 'https://www.mycurrency.net/=US'`, I get a normal file without errors, suggesting a problem with exrates.

**Comment by a1ess** [comment]
I noticed the same. I have a script running every day to fetch a rate that's not in ECB data. It fetched the rates correctly until December 27, from December 28 I get "Bad Gateway". Downloading the page manually works as expected, as indicated in the post above.

**Comment by hanna-kn** [comment]
It seems as if mycurrency.net now requires that a user agent is specified.

I've now made changes so that a user agent will be sent ("libqalculate/4.5.0"), and a document containing "Bad Gateway" will be considered a failure (old exchange rates will be preserved).

If the current mycurrency.net behaviour (which breaks all released versions of Qalculate) persists I will release a new version very soon.
