### ISSUE TITLE
Fixes on density units 

### ISSUE THREAD

**Issue by Matr1x-101** [Qalculate/libqalculate#506]
When doing a calculation like `14g/14cm^3`, the answer is `1 Mg/m^3`. This is undesirable; Mg/m^3 is almost never a good unit for density. The default unit for density should be g/cm^3 or kg/m^3.

**Comment by hanna-kn** [comment]
Automatic prefixes are quite primitive in Qalculate. The units m and (k)g use prefixes by default. It is currently not possible to specify if prefixes should be used for specific unit combinations (unnamed derived units), or which prefixes should be preferred for a unit. Otherwise it would have been preferable to specify, in the unit data, that kg/m^3 should not use prefixes by default, or that prefixes over kilo should be avoided for gram.

Until automatic prefixes have been improved, you should either disable automatic prefixes (e.g. using `set prefix 0`), or explicitly specify the desired unit (e.g. `14g/14cm³ to kg` or `14g/14cm³ to g/cm^3`)

**Comment by hanna-kn** [comment]
I've now made changes so that gram will not use a prefix higher than kilo by default. This fixes automatic density unit selection in most cases, and use of megagram (and larger) is uncommon.

Note that mass/volume is also used for measurements other than the density of different materials, and in these case other prefixes might be preferable (e.g. mg/m³ for the concentration of pollutants in the air).
