### ISSUE TITLE
Infer 'ans' keyword

### ISSUE THREAD

**Issue by Carath** [Qalculate/libqalculate#545]
Hello, could it be possible to infer the 'ans' keyword if an expression starts with an operator in qalc? Like below:

```
> 1+1
  2
> *2
  4
```

That is, instead of writing: ans *2

**Comment by hanna-kn** [comment]
The problem is that this would only fully work for multiplication. It is especially important not to infer 'ans' for minus, to allow input of negative numbers. `/` is used for explicit input of commands.

It might however be feasible to implement this behaviour for a subset of expressions, e.g. an operator followed by a single number.

**Comment by Carath** [comment]
Ok I get it, this is probably not worth the trouble.

Thanx anyway.
