### ISSUE TITLE
Feature request: allow numbers with infinite amount of decimal zeros to be used in integer-only arguments

### ISSUE THREAD

**Issue by baroxyton** [Qalculate/libqalculate#564]
some functions output numbers with an infinite amount of zeros. For example:

`log(19683) / log(3) = 9.00000000000000` (zeros continue at any precision)

it is equal to 9:
 ```py
log(19683) / log(3) = 9 # output: ((log(19683, e) / log(3, e)) = 9) = true
```

however it cannot be used in an integer-only function without manually rounding and leads to an error: `sum(3^x, 0, log(19683) / log(3))`

The feature request is to allow the program to automatically round numbers with infinite decimal zeros (ie. when the equality sign considers them the same to an integer) to the nearest integer when used in integer-only arguments, so that the example above would work without manual rounding

**Comment by hanna-kn** [comment]
Done.

With full internal precision, the result of `ln(19683) / ln(3)` is, with the default precision (10), an interval between 8.99999999999999999999999999999999999999853 and 9.00000000000000000000000000000000000000294.

Zero is not handled with the current solution (`sum(3^x, log(19683, 3) - 9, 0` results in an error), since it is not possible to determine the precision of an interval enclosing zero.

**Comment by baroxyton** [comment]
thank you!
