### ISSUE TITLE
dsolve can not solve dy/dx=y

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#617]
> dsolve(diff(y,x)=y) 

  error: Was unable to completely isolate y.
  error: Unable to solve differential equation.
  dsolve(diff(y, x) = y) = dsolve(diff(y, x) = y)

**Comment by hanna-kn** [comment]
dsolve() is unable to get any further than `ln(y) = x + C` because C is not assumed real. 

This has now been fixed. _C_ is now assumed real if _y_ is, and if _y_ cannot be isolated completely, the resulting equation will be returned in solve() function (e.g. `dsolve(diff(y, x) = y) = solve(ln(y) = x + C, y)` if y is not assumed real.

**Comment by hanna-kn** [comment]
```
> help dsolve

Function: Solve differential equation

dsolve(Equation[, Initial condition: function value (y)][, Initial condition: argument value (x)])

Solves a differential equation and returns the value of y(x). The derivative in the equation should be in the
format diff(y, x). Only first-order differential equations are currently supported.

Example: dsolve(2 * diff(y, x) - y = 4x, 5, 2) = 21e^(x/2) / e - 4x - 8

Arguments
Equation: a free value
Initial condition: function value (y): a free value (optional, default: undefined)
Initial condition: argument value (x): a free value (optional, default: 0)
```

**Comment by howaboutuser** [comment]
When will it support second-order differential equations? (Or will it?)
