### ISSUE TITLE
what is point of MathStructure->replace with 4 math args?

### ISSUE THREAD

**Issue by nick87720z** [Qalculate/libqalculate#67]
I eventually tried to use this functio for argument substitution in MathStructure with >=2 math unknowns.
I expected, that each single call will be faster, than 2 calls with 2 math arguments.
I use callgrind + kcachegrind for profiling, and my test has 1 single use of function with 4 arguments

++(misprinted enter)
cost of single replacement with 4 math args was 1.3 times bigger, than for variant with 2 math args.

**Comment by hanna-kn** [comment]
My tests show that the function for replacing two values is usually a few percent faster, but for the total time the difference should be negligible.

There is however a slight functional difference. The function for replacing two value will not replace occurrences of the original values in the replacement values. If you replace "x" with "y + 5" and y with "z" in "x*y", the result will be "(y+5)*z" instead of "(z+5)*z".

The function is only used in one place in the libqalculate code.

**Comment by nick87720z** [comment]
My apology, i was a bit pretty with conclusion. Plot part in my test involves only single-argument calls, while function with 4 args is called only once. After that i made more tests with much higher samples values.
While for 20000 samples best result is usually between 1.8 .. 2.4 (really it is rare below 2.0), with 400000 samples it was betweem 26 .. 28 s, what means 1.3 .. 1.4 per 20000. And for 1000 - between 0.8 .. 1.2 . Probably i will add few splots to test.

Last time i tried it it with following repeat: plot for [1:200] (per each functions) with samples=2000.
For single 1×400000 samples it made in 28.8 s, while for 200×2000 it took max 32s. I expected, that it will hang for at least minute... unfortunally, gnuplot doesn't allow for loops as standalone  commands - only inside plot, set or other similar commands.
