### ISSUE TITLE
fractional factors issue

### ISSUE THREAD

**Issue by nick87720z** [Qalculate/libqalculate#68]
There are two issues with factors, as well
In cli qalc: (-1)^(1 / 3) = approx. 0.5 + 0.8660254i
however: root(-1, 3) = -1 (so obvious)
Trying in qalculate-gtk, in always_exact mode, it leaves it as (-1)^0.3333...
For (-2)^(2/3) same (last) way gives: (-1)^0.6666... root(4, 3) .
For later case - i checked, that result is always real (non-complex) = root(4,3);
not mater, what is done first - power or root op.
Similar cases could be solved by representing factor in rational form, with following convertion:
x^(n/d) => root(x^n, d) or root(x, d)^n, depending on situation.

**Comment by hanna-kn** [comment]
By design cbrt() and root() always return the real root and fractional powers always return the principal root. In exact mode the result is divided into a complex and real part in a way that does not change the actual value.

Matlab (nthroot) and other software exhibit the same behaviour, while for example gnome-calculator appears inconsistent ((-8)^(1/3) =2, whiles (-8)^(2/3) returns −2−3,4641i which is neither the real nor principal root).
