### ISSUE TITLE
Proposal: allow default currency in the configuration

### ISSUE THREAD

**Issue by maximbaz** [Qalculate/libqalculate#78]
I use currency conversion a lot, but most of the time I want to convert everything to my local currency (danish crowns). Today I have to type `10 USD to DKK`, `30 EUR to DKK`. What I would like to have is to avoid typing the suffix every time, set my default currency as DKK in the `~/.config/qalculate/qalc.cfg`, so that I can simply type `10 USD`, hit <kbd>Enter</kbd> and it will give me e.g. `DKK 60.100823` instead of `$10`.

**Comment by hanna-kn** [comment]
With optimal unit conversion activated, currencies will now be automatically converted to the local currency.

**Comment by maximbaz** [comment]
Hmm, I am having troubles reproducing the fix, could you give me a hint?

I assume I have optimal unit conversion activated, because `help set` prints: 
`autoconversion    (none, optimal*, base, optimalsi, mixed)`

However, when running `10 USD` or `10 EUR` I still get results in dollars and euro correspondingly.

I even tried to override LC_ALL, yet still doesn't work:

```
❯ LC_ALL=en_US.UTF-8 src/qalc
> 10 EUR

  10 * euro = €10
```

How does one define or override the definition of the local currency?

**Comment by hanna-kn** [comment]
Fixed (I forgot that there are different optimal conversion modes).

**Comment by hanna-kn** [comment]
Fixed (I forgot that there are different optimal conversion modes).

**Comment by maximbaz** [comment]
Thank you, it works now! For future readers, the way you configure currency (on Linux) is by setting the `LC_MONETARY` environment variable. That way, even though my computer is configured for `en_US` locale for various reasons, I can tell `qalc` to use Danish currency by launching it like so:

```bash
$ LC_MONETARY=en_DK.UTF-8 LC_ALL= qalc -t "10 USD"
DKK 60.100823
```

P.S. In case you didn't leave these on purpose, there are a few `cout`'s left in the code that need to be removed afterwards 😉 

https://github.com/Qalculate/libqalculate/blob/784a456138ef507be18c96429c84422b958c2a5e/libqalculate/Calculator.cc#L3358

https://github.com/Qalculate/libqalculate/blob/784a456138ef507be18c96429c84422b958c2a5e/libqalculate/Calculator.cc#L3387

https://github.com/Qalculate/libqalculate/blob/784a456138ef507be18c96429c84422b958c2a5e/libqalculate/Calculator.cc#L3405

https://github.com/Qalculate/libqalculate/blob/784a456138ef507be18c96429c84422b958c2a5e/libqalculate/Calculator.cc#L3447

**Comment by maximbaz** [comment]
Closing because v2.4 is released 🎉 
Thanks once again!

**Comment by amosbird** [comment]
Is it possible to have default currency unit applied to the left operant? For instance, 

```
 ❯ env LC_MONETARY=zh_CN.UTF-8 qalc 123 dollar
123 * dollar = approx. CNY 862.41047

 ❯ env LC_MONETARY=zh_CN.UTF-8 qalc 123 CNY to dollar
123 * CNY = approx. $17.542690

 ❯ env LC_MONETARY=zh_CN.UTF-8 qalc 123 to dollar
123 = 123  < ----   I'd like to have 123 be interpreted as CNY here
```

**Comment by hanna-kn** [comment]
> Is it possible to have default currency unit applied to the left operant? For instance,
> 
> ```
>  ❯ env LC_MONETARY=zh_CN.UTF-8 qalc 123 dollar
> 123 * dollar = approx. CNY 862.41047
> 
>  ❯ env LC_MONETARY=zh_CN.UTF-8 qalc 123 CNY to dollar
> 123 * CNY = approx. $17.542690
> 
>  ❯ env LC_MONETARY=zh_CN.UTF-8 qalc 123 to dollar
> 123 = 123  < ----   I'd like to have 123 be interpreted as CNY here
> ```

Done. (This will also work for other types of units.)

**Comment by sethidden** [comment]
man i love qalc

**Comment by shodanx2** [comment]
Hello,

This thread is the top google result for 

`qalculate make $ default to currency`

I just pasted some calculation with dollar signs, and by default it assumes that I want USD to BRIT

But unless otherwise specified, I want CAD assumed both for input and output

<img width="798" height="1014" alt="Image" src="https://github.com/user-attachments/assets/43978993-9c98-4e6a-a6af-bb4a2db5a1e9" />

I tried reading this, but I can't figure out what I"m supposed to do ?

I then asked chatgpt, it said to go in the file menu, there is no file menu

https://chatgpt.com/share/68f644f6-b964-8005-b4b4-7c6e9845448d

It suggested to 

```
launch the app with the desired locale:
LC_MONETARY=en_CA.UTF-8 qalculate-gtk
```

Which, I don't think it should need to involve a console, also doesn't work since I'm in Bill Gate's prison

Now it says I should edit this file


`C:\Users\<YourUsername>\AppData\Roaming\qalculate\qalculate-gtk.cfg`

and look for something like 

```
optimal_units=...
currency=CAD
```


So, for the people coming in from google into this thread, can we have a straightforward solution at the end of this thread ?

**Comment by hanna-kn** [comment]
> Which, I don't think it should need to involve a console, also doesn't work since I'm in Bill Gate's prison

Why does your regional (Windows) settings specify British pounds as the currency? With regional format for "English (Canada)" selected (in Time & Language ➞ Language & Region) CAD will be used as the default currency in Qalculate.

The assumption that underlies the omission of a setting in Qalculate to select the default currency, is that few users would want to specify a different currency then the default of the system.

**Comment by shodanx2** [comment]
I think the question "qalculate make $ default to currency"
asks qalculate "you're not doing the right currency, let me change it"

I mean, maybe in some cases diagnosing the operating system is the easier way, but 

<img width="1543" height="1123" alt="Image" src="https://github.com/user-attachments/assets/744c1841-c766-49c7-96ac-347db7cca684" />

no in my case apparently

**Comment by hanna-kn** [comment]
> I mean, maybe in some cases diagnosing the operating system is the easier way, but

That is strange. I assume that you haven't changed anything under "Additional data, time & regional settings". When I change regional format the "English (Canada)" the default currency in Qalculate is also changed correctly (both in Windows 10 and Windows 11).

I will consider adding an option (at least editable in the configuration file) to change the default currency, unless I find an explanation for discrepancy.

**Comment by shodanx2** [comment]
Ok I think the issue is something called "Display Language" 

There is no "canadian english display language"  
It is US or UK, there is no CA for that particular setting

Also changing this setting is a SERIOUS ordeal

<img width="336" height="191" alt="Image" src="https://github.com/user-attachments/assets/3992b47f-5259-420f-a806-2e79baf18cc8" />

<img width="1305" height="784" alt="Image" src="https://github.com/user-attachments/assets/4f68784e-dc34-4ce9-8686-97caa5492255" />

<img width="570" height="718" alt="Image" src="https://github.com/user-attachments/assets/2e8ca572-8f8c-4ae7-aa39-fd6ba238ce5a" />

<img width="544" height="763" alt="Image" src="https://github.com/user-attachments/assets/a98d23df-3fdc-4cd9-92cf-aa0ebad0dce8" />

<img width="570" height="718" alt="Image" src="https://github.com/user-attachments/assets/8e0b0a8c-deb2-4cd9-8245-ee0911e6bf69" />

<img width="538" height="792" alt="Image" src="https://github.com/user-attachments/assets/7f2ec495-d7c2-40d6-bf47-28d926b022d1" />

<img width="518" height="315" alt="Image" src="https://github.com/user-attachments/assets/47e971fa-a17a-4af0-96f2-8482b9ba43c1" />

This is too much digging into setting and changing things and also it would be impossible if I didn't have root access to this computer, which is every computer I use outside of my home and it's usually impossible to ask or even find someone with root access that could even change this if they even could survive explaining why !

**Comment by shodanx2** [comment]
Also, in the other settings, it even says I have "canada display language" 

But that's !! ANOTHER !!  kind of "display language" that isn't the same as the previous one from the old control panel !

<img width="1543" height="1123" alt="Image" src="https://github.com/user-attachments/assets/29420c33-899f-4a8a-b2db-74199665a825" />

Windows is an incredible mess hehehe !

**Comment by shodanx2** [comment]
The first place I thought this might be, was here

<img width="824" height="1220" alt="Image" src="https://github.com/user-attachments/assets/5f0fab5f-81a3-4c0f-86ce-db295cc8c013" />

But it should also be here, which I just found here in the menu

<img width="1839" height="1125" alt="Image" src="https://github.com/user-attachments/assets/4861ab2b-c69a-44d5-9988-51c48c681470" />

I would suggest taking that preference/settings button out from the middle of the burger menu and giving it a dedicated gear icon button to the left of the burger menu

**Comment by hanna-kn** [comment]
I've now added an option to change default currency in qalculate-qt and qalculate-gtk (in preferences dialog).

**Comment by azizsayfiddin** [comment]
> I've now added an option to change default currency in qalculate-qt and qalculate-gtk (in preferences dialog).

Would be nice to have in qalc cli too.

**Comment by hanna-kn** [comment]
> > I've now added an option to change default currency in qalculate-qt and qalculate-gtk (in preferences dialog).
> 
> Would be nice to have in qalc cli too.

Done (in a5040e6).

**Comment by adrianinsaval** [comment]
> It suggested to
> 
> ```
> launch the app with the desired locale:
> LC_MONETARY=en_CA.UTF-8 qalculate-gtk
> ```
> 
> Which, I don't think it should need to involve a console, also doesn't work since I'm in Bill Gate's prison

you can set LC_MONETARY as an environment variable on windows, run `setx LC_MONETARY=en_CA.UTF-8` in a cmd prompt and it will save this for your user, you can run the app normally from the shortcut and it should work
